import {
    NAV_ITEM_TYPE_COLLAPSE,
    NAV_ITEM_TYPE_ITEM,
    NAV_ITEM_TYPE_TITLE,
} from '@/constants/navigation.constant'
import type { NavigationTree } from '@/@types/navigation'

const navigationConfig: NavigationTree[] = [
    {
        key: 'home',
        path: '/home',
        title: 'Home',
        translateKey: 'nav.home',
        icon: 'home',
        type: NAV_ITEM_TYPE_ITEM,
        authority: ['user'],
        subMenu: [],
    },

    {
        key: 'airtime',
        path: '',
        title: 'Airtime',
        translateKey: 'nav.data',
        icon: 'collapseMenu',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: ['user'],
        subMenu: [
            {
                key: 'airtime.direct',
                path: '/airtime/direct',
                title: 'Buy Airtime',
                translateKey: 'nav.airtime',
                icon: 'groupSingleMenu',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['user'],
                subMenu: [],
            },
            {
                key: 'airtime.pin',
                path: '/airtime/pin',
                title: 'Airtime Pin',
                translateKey: 'nav.airtime',
                icon: 'groupSingleMenu',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['user'],
                subMenu: [],
            },
        ],
    },
    {
        key: 'data',
        path: '/data',
        title: 'Buy Data',
        translateKey: 'nav.data.buy',
        icon: 'collapseMenu',
        type: NAV_ITEM_TYPE_ITEM,
        authority: ['user'],
        subMenu: [],
    },
    {
        key: 'bills',
        path: '',
        title: 'More Bills',
        translateKey: 'nav.bill.main',
        icon: 'collapseMenu',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: ['user'],
        subMenu: [
            {
                key: 'bill.cable',
                path: '/bill/cable',
                title: 'Cable',
                translateKey: 'bill.cable',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['user'],
                subMenu: [],
            },
            {
                key: 'bill.electricity',
                path: '/bill/electricity',
                title: 'Electricity',
                translateKey: 'bill.electricity',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['user'],
                subMenu: [],
            },
            {
                key: 'bill.education',
                path: '/bill/education',
                title: 'Education',
                translateKey: 'bill.education',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['user'],
                subMenu: [],
            },
        ],
    },

    {
        key: 'finance',
        path: '',
        title: 'finance',
        translateKey: 'nav.finance.main',
        icon: '',
        type: NAV_ITEM_TYPE_TITLE,
        authority: ['user'],
        subMenu: [
            {
                key: 'finance.withdraw',
                path: '/withdraw',
                title: 'Withdraw',
                translateKey: 'nav.finance.withdraw.main',
                icon: 'groupSingleMenu',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['user'],
                subMenu: [],
            },
            {
                key: 'finance.deposit',
                path: '/deposit',
                title: 'Deposit',
                translateKey: 'nav.finance.deposit',
                icon: 'groupSingleMenu',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['user'],
                subMenu: [],
            },
            {
                key: 'transaction.log',
                path: '/transaction/logs',
                title: 'Transaction Log',
                translateKey: 'nav.transaction.logs',
                icon: 'groupSingleMenu',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['user'],
                subMenu: [],
            },
        ],
    },
    {
        key: 'task',
        path: '',
        title: 'More Product',
        translateKey: 'nav.product.main',
        icon: 'groupCollapseMenu',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: ['user'],
        subMenu: [
            {
                key: 'exam.pin',
                path: '/user/social-task',
                title: 'Exam Pin',
                translateKey: 'nav.exam.pin',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['user'],
                subMenu: [],
            },
            {
                key: 'recharge.print',
                path: '/user/games',
                title: 'Recharge Printing',
                translateKey: 'nav.recharge.print',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['user'],
                subMenu: [],
            },
            {
                key: 'virtual.card',
                path: '/user/virtual/card',
                title: 'Virtual Card',
                translateKey: 'nav.virtual.card',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['user'],
                subMenu: [],
            },
            {
                key: 'upgrade.acc',
                path: '/user/post/ads',
                title: 'Upgrade Account',
                translateKey: 'nav.upgrade.acc',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['user'],
                subMenu: [],
            },
        ],
    },
]

export default navigationConfig
